services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/gateway:/app/gateway
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users
    ports:
      - "8080:8080"
    volumes:
      - ./users/users:/app/users
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --protected-mode no
    networks:
      - app-network

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge