services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/gateway:/app/gateway
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users
    volumes:
      - ./users/users:/app/users
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --protected-mode no
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  restapi:
    build:
      context: ./REST_API
      dockerfile: Dockerfile
    container_name: restapi
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./uploads:/uploads
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge