spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          autocommit: false

  servlet:
    multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 100MB

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html